server:
      port: 80
      tomcat:
        uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    encoding: UTF-8
    content-type: text/html; charset=utf-8
    mode: HTML5
    suffix: .html
    cache: false
      
        
  profiles:
    active: dev
  